Update README.md
alphagov/forms-runner pull request #398
Opened 2023-08-04 10:27 UTC by lfdebrux

### What problem does this pull request solve?

Our README.md file in our app repos are (in my opinion) a bit messy and could use some re-organising to make it the crucial information more prominent and the rest easier to find.

This PR makes changes to the forms-runner repo, similar to the changes made to the forms-admin readme in alphagov/forms-admin#553 and alphagov/forms-admin#568.

2023-08-07 09:14 UTC, cmcnallygds commented on README.md
> +The app tests are written with [rspec-rails] and you can run them with:
```suggestion
The app tests are written with [rspec-rails], and you can run them with:
```

2023-08-07 09:15 UTC, cmcnallygds commented on README.md
> +We use [RuboCop GOV.UK] for linting code. To autocorrect issues run:
```suggestion
We use [RuboCop GOV.UK] for linting code. To autocorrect issues, run:
```

2023-08-07 09:17 UTC, cmcnallygds commented on README.md
> +Redis sessions can be enabled by providing the redis connection URL in the environment variable `REDIS_URL`
Could we make this active? "You can enable Redis sessions by providing..."?

2023-08-07 09:49 UTC, cmcnallygds commented on README.md
> +If you want to deliberately raise an exception to test, uncomment out the triggers in the [Sentry initializer script](config/initializers/sentry.rb). Whenever you run the app errors will be raised an
```suggestion
If you want to deliberately raise an exception to test, uncomment out the triggers in the [Sentry initializer script](config/initializers/sentry.rb). Whenever you run the app, errors will be raised and should also come through on Sentry.
```

2023-08-07 09:50 UTC, cmcnallygds commented on README.md
> +The forms-runner app is containerised (see [Dockerfile](Dockerfile)) and can be deployed however you would normally deploy a containerised app.
```suggestion
The forms-runner app is containerised (see [Dockerfile](Dockerfile)) and can be deployed in the same way you'd normally deploy a containerised app.
```

2023-08-07 09:53 UTC, cmcnallygds commented on README.md
> +We host our apps using Amazon Web Services (AWS). You can [read about how deployments happen on our team wiki, if you have access](https://github.com/alphagov/forms-team/wiki/Deploying-code-changes-A
```suggestion
We host our apps using Amazon Web Services (AWS). You can [read about how deployments happen on our team wiki](https://github.com/alphagov/forms-team/wiki/Deploying-code-changes-AWS),  if you have access.
```

2023-08-07 09:55 UTC, cmcnallygds commented on README.md
> +- Custom app logging should be made via the [LogEventService](./app/services/log_event_service.rb) and [EventLogger](./app/lib/event_logger.rb). This is independent to any Lograge configuration.
```suggestion
- Custom app logging should be made through the [LogEventService](./app/services/log_event_service.rb) and [EventLogger](./app/lib/event_logger.rb). This is independent from any Lograge configuration.
```

2023-08-07 09:57 UTC, cmcnallygds commented on README.md
> +- The output format is JSON using the [JsonLogFormatter](./app/lib/json_log_formatter.rb) to enable simpler searching and visbility, especially in Splunk.
```suggestion
- The output format is JSON, using the [JsonLogFormatter](./app/lib/json_log_formatter.rb) to enable simpler searching and visbility, especially in Splunk.
```

2023-08-07 11:20 UTC, lfdebrux commented on README.md
> +- Custom app logging should be made via the [LogEventService](./app/services/log_event_service.rb) and [EventLogger](./app/lib/event_logger.rb). This is independent to any Lograge configuration.
The `LogEventService` has a set of 'helper' functions that should be used when a developer wants to log something; for example, at https://github.com/alphagov/forms-runner/blob/5c45a0a67fae394ff0ba8caceb80d4cfc27aa001/app/controllers/forms/page_controller.rb#L17 we use the `log_page_save` method to create a print a log message about a user filling in a form.

So I think it's more accurate to say that logs are made with the service. Maybe it could be "Custom app log messages should be made via the..."? Or if we want it to be active, something like:

```suggestion
- You should use the [LogEventService](./app/services/log_event_service.rb) and [EventLogger](./app/lib/event_logger.rb) to create any custom log messages. This is independent to any Lograge configuration.
```

2023-08-07 11:27 UTC, cmcnallygds commented on README.md
> +- Custom app logging should be made via the [LogEventService](./app/services/log_event_service.rb) and [EventLogger](./app/lib/event_logger.rb). This is independent to any Lograge configuration.
Yes, I think this works!

2023-08-07 11:28 UTC, cmcnallygds commented on README.md
> +- HTTP access logs are managed using [Lograge](https://github.com/roidrage/lograge) and configured within [the application config](./config/application.rb).
You should manage HTTP access logs using [Lograge] (https://github.com/roidrage/lograge) and configure them within [the application config](./config/application.rb).

2023-08-07 11:34 UTC, cmcnallygds requested changes
I've suggested some changes for style and clarity

2023-08-08 08:53 UTC, lfdebrux commented on README.md
> +- HTTP access logs are managed using [Lograge](https://github.com/roidrage/lograge) and configured within [the application config](./config/application.rb).
I'm not sure what the word 'manage' means here, I think it would be clearer if it were

```suggestion
- You should should configure HTTP access logs in [the application config](./config/application.rb), using [Lograge](https://github.com/roidrage/lograge).
```

2023-08-08 12:49 UTC, cmcnallygds commented on README.md
> +- HTTP access logs are managed using [Lograge](https://github.com/roidrage/lograge) and configured within [the application config](./config/application.rb).
Looks good

2023-08-09 08:57 UTC, thomasiles commented on README.md
>  - a running [PostgreSQL](https://www.postgresql.org/) database
```suggestion
```

Do we need this here? The DB is needed for the API project, which is linked.

2023-08-09 09:16 UTC, lfdebrux commented on README.md
>  - a running [PostgreSQL](https://www.postgresql.org/) database
Oh good point, I copied this from forms-admin which of course does need the database.

2023-08-09 09:21 UTC, thomasiles approved these changes
good work, its a lot cleaner

2023-08-09 09:25 UTC, merged